### ISSUE TITLE
add commit/author local timestamp

### ISSUE THREAD

**Issue by fayazg** [LF-Engineering/insights-connector-git#72]
Add `authored_local_timestamp` and `committed_local_timestamp` to commit objects in the same format that `git log` returns (with timezone offset intact).

**Comment by fayazg** [comment]
[This file](https://s3.console.aws.amazon.com/s3/object/datalake-input-prod?region=us-east-2&prefix=insights/git/commits/2023/01/10/commit.created-1673391963737476272-znmhHWNe.json) was created on `January 10, 2023, 16:06:04 (UTC-07:00)` but the local timestamp values for events are in the following format (below is for the last event):

```
"authored_local_timestamp": "2023-01-10T17:25:20-05:00",
"committed_local_timestamp": "2023-01-10T17:25:20-05:00"
```

- format on those don't include the timezone offset of -0700
- they are the sync time and not actual authored/committed timestamps, it should be `Tue Aug 11 22:36:51 2015 -0700`

**Comment by lukaszgryglicki** [comment]
They do have TZoffset, see: `2023-01-10T17:25:20-05:00`, tz offset is `-05:00` - I'm OK with this format, it is even better than originally requested IMHO because it looks waaaaaaaay more standard.
@fayazg @khalifapro - if we decide to use this format, please update [DL-801](https://jira.linuxfoundation.org/browse/DL-801) ticket specs.

**Comment by lukaszgryglicki** [comment]
@fayazg @khalifapro so I'm expecting a fixed format for this, examples:
- `2023-01-10T17:25:20-05:00`.
- `2023-01-10T17:25:20+01:30`.
- `2023-01-10T17:25:20 00:00`.
My implementation will be based on this.

**Comment by lukaszgryglicki** [comment]
It is better that the raw one returned from git log and more standardized, I've assumed this format in my work, @khalifapro is also OK with it.
